on:
  push:
    branches:
      - main
jobs:
  build:
    uses: jeffscottbrown/tinyjs/.github/workflows/compile.yml@main
    with:
      glob: "src/**/*.tjs"
      platforms: '["ubuntu-latest","macos-latest"]'
      emit_ir: true
